baseurl = "http://clarencemills.com/"
languageCode = "en-us"
title = "Clarence Mills technologist"
publishdir = "public"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    	# information about you and your website.
	name = "Clarence Mills"
	description = "Technologist"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Technologist"

		[params.navigation.links]
			about     	= "About"
			services	= "Online Presence"
			portfolio	= "Resume"
			contact   	= "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Clarence Mills"
		subtitle   = "Always render more and better service than is expected of you, no matter what your task may be - Og Mandino"
		buttonText = "A little about myself"

	# About section
	[params.about]
		headline    = "Consultant - Entrepeneur - Advisor"
		description = "I am a consumer, advisor and evangelist of open source software and technology based solutions"
		buttonText  = "Technologist"


	# Service section
	[params.services]
		headline = " Contribution"

        [[params.services.list]]
	  icon = "fa-newspaper-o"
	  title = "Online Network Tools"
	  description = "www.fixyourip.com"

	[[params.services.list]]
	 icon = "fa-newspaper-o"
	 title = "Code"
	 description = "GitHUB repository"

	[params.aside]
	 headline = "Career Details"

	[params.aside.button]
     	 text = "My Resume"
	 link = "//"

	# Contact section
	[params.contact]
		headline = "Contact Details"
		description = "Questions, I have answers."
		phone = "647-794-5083"
		email = "cmills@clarencemills.com"
